version: '2'
services:
  divino-itil:
    image: highlanderdantas/divino-itil:1.0
    restart: always
    environment: 
      - MONGOURL=${mongo_url}:27017
      - JUNIA_TIME_URL=${juniatime_url}
      - SLACK_P1=${slack_p1}
      - SLACK_P2=${slack_p2}
      - SLACK_P3=${slack_p3}
    labels:
      io.rancher.container.pull_image: always
    ports:
      - "8881:8881"
    drain_timeout_ms: 10000
    health_check:
        port: 8881
        request_line: GET / HTTP/1.0
        interval: 50000
        initializing_timeout: 50000
        reinitializing_timeout: 50000
        unhealthy_threshold: 3
        strategy: recreate
        healthy_threshold: 1
        response_timeout: 50000
    


    