jiva-w:
  image: jivagestaoempresarial/jivaw:1.0
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - PACOTE_JIVAW=jiva-w_3.19.27b24.pkg
    - TIPO_SERVIDOR=WILDFLY
    - TIPO_BD=Oracle
  links:
    - sas
  volumes: 
    - /home/mgeweb/dados/{{ .Stack.Name }}/repositorio/:/home/mgeweb/repositorio # Repositório de arquivos
    - /home/mgeweb/dados/{{ .Stack.Name }}/logs/:/home/mgeweb/wildfly_producao/standalone/log # logs do JBOSS
    - /home/mgeweb/dados/{{ .Stack.Name }}/SanNFe/:/home/mgeweb/SanNFe # Certificados do SanNFe
    - /home/mgeweb/pacotes-sannfe:/home/mgeweb/pacotes-sannfe/  # Pacotes do SanNFe
    - /home/mgeweb/pacotes-jivaw:/home/mgeweb/sankhyaw-dpm/pkgs # Pkgs Jiva-W
  command: ["/bin/sh","-c", "sed -i 's/-Xms1024M -Xmx1024M/${memoria_jboss}/g' /home/mgeweb/wildfly_producao/bin/standalone.conf && sudo mkdir -p /home/mgeweb/repositorio/impressao/ && sudo chown -R mgeweb:mgeweb /home/mgeweb/sankhyaw-dpm/ /home/mgeweb/pacotes-sannfe && java -jar /home/mgeweb/DPM/docker-package-manager.jar && sudo /home/mgeweb/./sannfe.sh && sudo chown mgeweb:mgeweb / && sudo chown -R mgeweb:mgeweb /home/mgeweb/SanNFe /home/mgeweb/wildfly_producao/standalone/log /home/mgeweb/repositorio && sleep 2 && /home/mgeweb/wildfly_producao/bin/./standalone.sh -Djape.lazy.init=true -Djape.lob.fields.as.lazy=true -Djape.ignore.ligacao.inconsistente=true"]
  mem_limit: '1536m' 

sas:
  image: jivagestaoempresarial/sas:1.0
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - IP_CONTAINER=${agent_ip}
  volumes: 
    - /home/mgeweb/pacotes-sas:/home/mgeweb/pacotes-sas/  # Pacotes do SAS
  command: ["/bin/sh","-c", "sudo chown -R mgeweb:mgeweb /home/mgeweb/pacotes-sas && java -jar /opt/DSM/docker-sas-manager.jar && tar -xzf /tmp/SAS.tar.gz -C /opt/ && sleep 2 && /opt/./run-sas.sh && sleep 2 && tail -f /opt/SAS*/log/server*.log"]