jiva-w:
  image: jivagestaoempresarial/jivaw:1.0
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    #- PACOTE_JIVAW=jiva-w_3.20b315.pkg
    - PACOTE_JIVAW=${pacote_jivaw}
    - TIPO_SERVIDOR=WILDFLY
    - TIPO_BD=Oracle
  links:
    - sas
  volumes: 
    - /home/mgeweb/compartilhado/clientes/{{ .Stack.Name }}/repositorio/:/home/mgeweb/repositorio # Repositório de arquivos
    - /home/mgeweb/compartilhado/clientes/{{ .Stack.Name }}/logs/:/home/mgeweb/wildfly_producao/standalone/log # logs do JBOSS
    - /home/mgeweb/compartilhado/clientes/{{ .Stack.Name }}/SanNFe/:/home/mgeweb/SanNFe # Certificados do SanNFe
    - /home/mgeweb/compartilhado/pacotes/sannfe:/home/mgeweb/pacotes-sannfe/  # Pacotes do SanNFe
    - /home/mgeweb/compartilhado/pacotes/jivaw:/home/mgeweb/sankhyaw-dpm/pkgs # Pkgs Jiva-W
  command: ["/bin/sh","-c", "sed -i 's/-Xms1024M -Xmx1024M/${memoria_jboss}/g' /home/mgeweb/wildfly_producao/bin/standalone.conf && mkdir -p /home/mgeweb/wildfly_producao/tmp && echo 'JAVA_OPTS=\"$$JAVA_OPTS -Duser.home=/home/mgeweb/ -Djava.io.tmpdir=/home/mgeweb/wildfly_producao/tmp\"' >> /home/mgeweb/wildfly_producao/bin/standalone.conf && mkdir -p /home/mgeweb/repositorio/impressao/ && java -jar /home/mgeweb/DPM/docker-package-manager.jar && sudo chown mgeweb:mgeweb / && /home/mgeweb/./sannfe.sh && sleep 2 && /home/mgeweb/wildfly_producao/bin/./standalone.sh -Djape.lazy.init=true -Djape.lob.fields.as.lazy=true -Djape.ignore.ligacao.inconsistente=true"]
  mem_limit: '1536m' 
  mem_swappiness: 10 # Irá usar o swap apenas quando tiver 10% de mem disponível

sas:
  image: jivagestaoempresarial/sas:1.0
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - UPD_IP_SAS=${sas_delphi}
  volumes: 
    - /home/mgeweb/compartilhado/pacotes/sas:/home/mgeweb/pacotes-sas/  # Pacotes do SAS
  command: ["/bin/sh","-c", "java -jar /opt/DSM/docker-sas-manager.jar && tar -xzf /tmp/SAS.tar.gz -C /opt/ && sleep 2 && /opt/./run-sas.sh && sleep 2 && tail -f /opt/SAS*/log/server*.log"]
