version: '2'
services:
  celson-implanter:
    image: highlanderdantas/celson-implanter:1.0
    restart: always
    environment: 
      - MONGOURL=mongo:27017
      - ORIGIN=${origin}
      - ACCESS_KEY_PRD=${ACCESS_KEY_PRD}
      - SECRET_KEY_PRD=${SECRET_KEY_PRD}
      - REGION_PRD=${REGION_PRD}
      - BUCKET_PRD=${BUCKET_PRD}
      - ACCESS_KEY_TST=${ACCESS_KEY_TST}
      - SECRET_KEY_TST=${SECRET_KEY_TST}
      - REGION_TST=${REGION_TST}
      - BUCKET_TST=${BUCKET_TST}
    links:
      - mongo
    labels:
      io.rancher.container.pull_image: always
    ports:
      - "8080:8080"
    drain_timeout_ms: 10000
    health_check:
        port: 8880
        request_line: GET / HTTP/1.0
        interval: 50000
        initializing_timeout: 50000
        reinitializing_timeout: 50000
        unhealthy_threshold: 3
        strategy: recreate
        healthy_threshold: 1
        response_timeout: 50000
  mongo:
    image: mongo:3.4
    restart: always
    volumes: 
      - /home/mgeweb/monitoring/mongo:/data/db
    ports: 
      - "27017:27017"
    


    