version: '2'
catalog:
  name: "Jiva-W"
  version: "TH-V2.0"
  description: "VERSÃO EM TESTE"
  questions:
    # Pacote Instalação
    - variable: "pacote_jivaw"
      label: "Pacote para instalação"
      description: |
        Pacote que será instalado (será buscado no ftp-sankhya)
      type: "string"
      required: true

    # Banco de Dados
    - variable: tp_bd
      label: "Tipo do Banco de Dados"
      description: |
        Tipo do Banco Dados
      type: enum
      default: ORACLE
      required: true
      options:
        - ORACLE
        - SQLSERVER

    - variable: "ip_bd"
      label: "IP do Banco de Dados"
      description: |
        IP no qual está instalado o Banco de Dados
      type: "string"
      required: true

    - variable: "porta_bd"
      label: "Porta do Banco de Dados"
      description: |
        Porta no qual está instalado o Banco de Dados | 
        PORTA PADRAO ORACLE 1521 | 
        PORTA PADRAO SQLSERVER 1433 |
      type: "string"
      default: ""
      required: true

    - variable: "sid_bd"
      label: "SID do Banco de Dados"
      description: |
        SID do Banco de Dados | 
        SID PADRAO ORACLE ORCL | 
        SID PADRAO SQLSERVER MYSQLSERVER
      type: "string"
      default: ""
      required: true

    - variable: "usuario_bd"
      label: "Usuário do Banco de Dados"
      description: |
        Usuário do Banco de Dados
      type: "string"
      required: true

    - variable: "senha_bd"
      label: "Senha do Banco de Dados"
      description: |
        Senha do Banco de Dados
      type: "password"
      required: true

    # Memoria da Aplicação
    - variable: "memoria_jboss"
      label: "Memória de inicialização do WildFly"
      description: |
        Memória de inicialização do WildFly
      type: enum
      options:
        - -Xms512m -Xmx1150m
        - -Xms512m -Xmx1304m
        - -Xms1024m -Xmx1536m
        - -Xms1024m -Xmx2048m
      required: true

    - variable: memory_container
      label: "Quantidade de memória máxima do container"
      description: Memória máxima que será alocada para o container. Ao exaurir memória RAM será utilizado o SWAP do sistema operacional.
      type: string
      default: "1536"
      required: true

    # Outras Aplicações
    - variable: chave_cliente
      label: "Chave SAS do cliente?"
      description: "Chave do cliente"
      type: string
      default: ""

    - variable: max_size
      label: "Limite de registros"
      description: "limita a quantidade de registros em 2000 para nao prejudicar a performance e a memoria do jiva-w"
      type: string
      default: "2000"

    - variable: sannfe_enabled
      label: "Habilitar SanNfe?"
      description: "Caso seja marcado true irá realizar o download do SanNfe "
      type: boolean
      default: false
      required: true

    - variable: sas_delphi
      label: "Cliente possui Delphi?"
      description: Caso seja marcado true o container do SAS não irá atualizar o parâmetro IPSERVACESS
      type: boolean
      default: false
      required: true

    - variable: data_sync
      label: "Cliente possui Data Sync?"
      description: Caso seja marcado true irá subir um container para o Data Sync
      type: boolean
      default: false
      required: true

    - variable: e_social
      label: "Cliente possui eSocial?"
      description: Caso seja marcado true irá subir um container com o SanESocial
      type: boolean
      default: false
      required: true
