version: '2'
services:
  juniatime:
    image: danmasilva/juniatime:3.6
    restart: always
    environment: 
      - MONGOURL=mongo:27017
      - ORIGIN=${origin}
      - WEBHOOK=${slack_webhook}
    links:
      - mongo
    labels:
      io.rancher.container.pull_image: always
    ports:
      - "8880:8880"
  mongo:
    image: mongo:3.4
    restart: always
    volumes: 
      - /home/mgeweb/monitoring/mongo:/data/db
    ports: 
      - "27017:27017"
  mongo-backup:
    image: danmasilva/mongo-juniatime:1.6
    restart: always
    volumes:
      - /home/mgeweb/compartilhado/mongo-backups:/etc/backups
    links:
      - mongo
    


    